sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t benjamistan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true benjamistan/react-test npm test

after_success:
  - docker build -t benjamistan/docker-client ./client
  - docker build -t benjamistan/docker-nginx ./nginx
  - docker build -t benjamistan/docker-server ./server
  - docker build -t benjamistan/docker-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push benjamistan/docker-client
  - docker push benjamistan/docker-nginx
  - docker push benjamistan/docker-server
  - docker push benjamistan/docker-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-3
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-eu-west-3-323528688928
  bucket_path: docker-complex2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY